/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.local.interfaces;

import com.usr.objects.Tfleet;
import java.awt.Point;

/**
 *
 * @author sirbobby
 */
public class TmainWindow extends javax.swing.JFrame {

    /**
     * Creates new form TmainWindow
     */
    public TmainWindow() {
        String direction = "/com/usr/resorcs/5horizontal.jpg";
        String direction1 = "/com/usr/resorcs/2vertical.jpg";
        barco = new Tfleet(direction,direction1,30, 30, 40, 40,new boolean[] {true,true,true,true},false, false);
        this.clicked = false;
        this.mouseCount = 0 ;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        Point point = jPanel1.getMousePosition();
        if (evt.getButton() == 1) mouseCount++;
        if (mouseCount == 1) {
            if (evt.getButton() == 3) {
                barco.setOrientation(!barco.getOrientation());
                if (barco.getOrientation()) {
                barco.setImgHorizontalX(jPanel1.getMousePosition().x);
                barco.setImgHorizontalY(jPanel1.getMousePosition().y);
                }
                else {
                    barco.setImgVerticalX(jPanel1.getMousePosition().x);
                    barco.setImgVerticalY(jPanel1.getMousePosition().y);
                }
            }
            if (barco.getOrientation()) {
                if (point.x > barco.getImgHorizontalX()  && point.x <(barco.getImgHorizontalX() + barco.getImgHorizontalX1())) {
                    if (point.y > barco.getImgHorizontalY()  && point.y <(barco.getImgHorizontalY() + barco.getImgHorizontalY1())) {
                        clicked = true;
                    }
                }
            }
            else {
                if (point.x > barco.getImgVerticalX()  && point.x <(barco.getImgVerticalX() + barco.getImgVerticalX1())) {
                    if (point.y > barco.getImgVerticalY()  && point.y <(barco.getImgVerticalY() + barco.getImgVerticalY1())) {
                        clicked = true;
                    }
                }
            }
        }
        else {
            mouseCount = 0;
            clicked = false;
        }
        barco.paint(jPanel1.getGraphics());
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        // TODO add your handling code here:
        if (clicked) {
            if (barco.getOrientation()) {
                barco.setImgHorizontalX(jPanel1.getMousePosition().x);
                barco.setImgHorizontalY(jPanel1.getMousePosition().y);
            }
            else {
                barco.setImgVerticalX(jPanel1.getMousePosition().x);
                barco.setImgVerticalY(jPanel1.getMousePosition().y);
            }
        }
        //repaint();
        barco.paint(jPanel1.getGraphics());
    }//GEN-LAST:event_jPanel1MouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TmainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TmainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TmainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TmainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            TmainWindow frame = new TmainWindow();
            frame.setVisible(true);
            frame.setResizable(false);
            frame.setLocationRelativeTo(null);
        });
    }
    private boolean clicked;
    private int mouseCount;
    private final Tfleet barco;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
